In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sc

In [3]:
df = pd.read_csv("Healthcare.csv")

In [4]:
df.shape

(5000, 7)

In [5]:
df.head()

,Patient_ID,Age,Gender,Glucose_mg_dL,Blood_Pressure_mmHg,BMI,Disease_Status
0,1,58,Male,118,144,26.8,Heart Disease
1,2,NaN,Male,196,147,30.7,Diabetes + Heart Disease
2,3,45,Male,104,136,NaN,Diabetes
3,4,44,Male,79,138,20.9,Heart Disease
4,5,72,Male,114,133,25.3,Heart Disease

In [6]:
df.isnull().sum()

Patient_ID               0
Age                     81
Gender                  99
Glucose_mg_dL           96
Blood_Pressure_mmHg     81
BMI                    104
Disease_Status          60
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           5000 non-null   int64
 1   Age                  4919 non-null   str
 2   Gender               4901 non-null   str
 3   Glucose_mg_dL        4904 non-null   str
 4   Blood_Pressure_mmHg  4919 non-null   str
 5   BMI                  4896 non-null   str
 6   Disease_Status       4940 non-null   str
dtypes: int64(1), str(6)
memory usage: 422.3 KB

In [8]:
df['Age'] = df['Age'].fillna(25)

In [9]:
df['Age'] = df['Age'].replace("45 years",45)
df['Age'] = df['Age'].replace("fifty",45)
df['Age'] = df['Age'].replace("unknown",26)

In [10]:
df['Age'] = df['Age'].replace(26,47)

In [11]:
df['Age'] = df['Age'].astype(int)

In [12]:
df.head(2)

,Patient_ID,Age,Gender,Glucose_mg_dL,Blood_Pressure_mmHg,BMI,Disease_Status
0,1,58,Male,118,144,26.8,Heart Disease
1,2,25,Male,196,147,30.7,Diabetes + Heart Disease

In [13]:
df['Blood_Pressure_mmHg'] = df['Blood_Pressure_mmHg'].fillna(78)

In [14]:
df.head()

,Patient_ID,Age,Gender,Glucose_mg_dL,Blood_Pressure_mmHg,BMI,Disease_Status
0,1,58,Male,118,144,26.8,Heart Disease
1,2,25,Male,196,147,30.7,Diabetes + Heart Disease
2,3,45,Male,104,136,NaN,Diabetes
3,4,44,Male,79,138,20.9,Heart Disease
4,5,72,Male,114,133,25.3,Heart Disease

In [15]:
df['Blood_Pressure_mmHg'] = df['Blood_Pressure_mmHg'].replace('unknown',110)

In [16]:
df['Blood_Pressure_mmHg'] = df['Blood_Pressure_mmHg'].replace('130 mmHg',115)

In [17]:
df['Blood_Pressure_mmHg'] = df['Blood_Pressure_mmHg'].replace('140/90',120)

In [18]:
df['Blood_Pressure_mmHg'] = df['Blood_Pressure_mmHg'].astype(int)

In [19]:
df['Gender'].unique()

<ArrowStringArray>
['Male', 'Female', nan, ' female', ' male', 'female ', 'Male ', 'FEMALE']
Length: 8, dtype: str

In [20]:
df['Gender'] = df['Gender'].replace(" female","Female")
df['Gender'] = df['Gender'].replace("female ","Female")
df['Gender'] = df['Gender'].replace("FEMALE","Female")
df['Gender'] = df['Gender'].replace(" male","Male")
df['Gender'] = df['Gender'].replace("Male ","Male")

In [21]:
df['Gender'].isnull().sum()

np.int64(99)

In [22]:
df.dropna(subset=['Gender'], inplace=True)

In [23]:
df.head()

,Patient_ID,Age,Gender,Glucose_mg_dL,Blood_Pressure_mmHg,BMI,Disease_Status
0,1,58,Male,118,144,26.8,Heart Disease
1,2,25,Male,196,147,30.7,Diabetes + Heart Disease
2,3,45,Male,104,136,NaN,Diabetes
3,4,44,Male,79,138,20.9,Heart Disease
4,5,72,Male,114,133,25.3,Heart Disease

In [24]:
df['BMI'] = df['BMI'].fillna(17)

In [25]:
df['BMI'] = df['BMI'].replace("unknown",18)
df['BMI'] = df['BMI'].replace("thirty",30)
df['BMI'] = df['BMI'].replace("28.5 kg/m2",29)

In [26]:
df['BMI'] = df['BMI'].astype(float)

In [27]:
df['Disease_Status'].unique()

<ArrowStringArray>
[           'Heart Disease', 'Diabetes + Heart Disease',
                 'Diabetes',                  'Healthy',
           ' HEART DISEASE',                        nan,
                  'HEALTHY',                 'diabetes',
                 'Healthy ', 'diabetes + heart disease']
Length: 10, dtype: str

In [28]:
df['Disease_Status'] = df['Disease_Status'].replace(" HEART DISEASE","Heart Disease")
df['Disease_Status'] = df['Disease_Status'].replace("diabetes + heart disease","Diabetes + Heart Disease")
df['Disease_Status'] = df['Disease_Status'].replace("diabetes","Diabetes")
df['Disease_Status'] = df['Disease_Status'].replace("diabetes","Diabetes")
df['Disease_Status'] = df['Disease_Status'].replace("Healthy ","Healthy")

In [29]:
df.dropna(subset=['Disease_Status'], inplace=True)

In [30]:
df['Disease_Status'].isnull().sum()

np.int64(0)

In [31]:
df.shape

(4842, 7)

In [32]:
df = df.to_csv("Clean_healthcare.csv")